### PR TITLE
Reduce the compose image size

### LINKED ISSUE #128: Reduce the size of compose images
Currently, the compose image size is more than 500mb, but the official image is less than 100mb.

### PR DESCRIPTION
**Pull request by cherrycl**
Signed-off-by: Cherry Wang <cherry@iotechsys.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/edgexfoundry/ci-management/blob/master/.github/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Added labels
## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Sandbox Testing
Test Links : https://jenkins.edgexfoundry.org/sandbox/view/All/job/edgex-compose-build/1/

### CODE REVIEW

**Comment by cherrycl** [comment]
Could anyone help review this PR?

**Comment by cloudxxx8** [comment]
@ernestojeda we made a change to improve the compose image.  could you please help review it?
thanks.

**Comment by cloudxxx8** [comment]
@ernestojeda could you please help take a look?  thanks

**Comment by cloudxxx8** [comment]
@ernestojeda and @jamesrgregg , since we have released Geneva, could you please help merge this PR?  It could improve the performance of blackbox tests.
Thanks.

**Comment by cloudxxx8** [comment]
@lranjbar ,@ernestojeda and @jamesrgregg could you please help merge this PR? thanks.

**Pull request merged**
