### PR TITLE
Add lftools base image

### PR DESCRIPTION
**Pull request by lranjbar**
Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>

### CODE REVIEW

**Comment by ernestojeda** [comment]
recheck

**Comment by jamesrgregg** [comment]
Seems like the build failed because it's looking for arm stage. Do we plan to create an arm based build image as well?

**Comment by lranjbar** [comment]
I need to talk to Ernesto to understand how the builds are working for this repository. I wasn't sure if lftools would need an arm build. This image is to encapsulate lftools and sigul inside its own container when we call it.

@ernestojeda @MightyNerdEric

**Comment by lranjbar** [comment]
Close for now

**Comment by lranjbar** [comment]
recheck

**Pull request merged**
